import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MantineProviderComponent from "../_components/providers/MantineProvider";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import './globals.css';
import ToastProvider from "../_components/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProviderComponent>
          <ToastProvider />
          { children }
        </MantineProviderComponent>
      </body>
    </html>
  );
}
